exports.dogs = [
    {url: 'https://imgur.com/vZpl0wz', breed: 'Affenpinscher'},
    {url: 'https://imgur.com/yJrmXwu', breed: 'Affenpinscher'},
    {url: 'https://imgur.com/toPER0k', breed: 'Afghan Hound'},
    {url: 'https://imgur.com/0GkxKPJ', breed: 'Afghan Hound'},
    {url: 'https://imgur.com/EiilTLI', breed: 'Africanis'},
    {url: 'https://imgur.com/SnGFAoL', breed: 'Africanis'},
    {url: 'https://imgur.com/so71NSQ', breed: 'Aidi'},
    {url: 'https://imgur.com/iL2Ik76', breed: 'Aidi'},
    {url: 'https://imgur.com/rhqps0L', breed: 'Airedale Terrier'},
    {url: 'https://imgur.com/mTAUQfY', breed: 'Airedale Terrier'},
    {url: 'https://imgur.com/kHWLhjJ', breed: 'Akbash Dog'},
    {url: 'https://imgur.com/0sEk0IX', breed: 'Akbash Dog'},
    {url: 'https://imgur.com/oeZOX9l', breed: 'Akita Inu'},
    {url: 'https://imgur.com/MBJC4VG', breed: 'Akita Inu'},
    {url: 'https://imgur.com/Vye1Jzc', breed: 'Akita Inu'},
    {url: 'https://imgur.com/JgR8S85', breed: 'Akita Inu'},
    {url: 'https://imgur.com/Bdak8bM', breed: 'Alangu Mastiff'},
    {url: 'https://imgur.com/tEWuHTd', breed: 'Alano Español'},
    {url: 'https://imgur.com/X8WORyf', breed: 'Alano Español'},
    {url: 'https://imgur.com/WUZhnHa', breed: 'Alano Español'},
    {url: 'https://imgur.com/ztiuoCv', breed: 'Alapaha Bulldog'},
    {url: 'https://imgur.com/aCUu1mK', breed: 'Alapaha Bulldog'},
    {url: 'https://imgur.com/65FcDmT', breed: 'Alaskan Klee Kai'},
    {url: 'https://imgur.com/A9xXCug', breed: 'Alaskan Klee Kai'},
    {url: 'https://imgur.com/8vlC6zu', breed: 'Alaskan Malamute'},
    {url: 'https://imgur.com/nUBEVNP', breed: 'Alaskan Malamute'},
    {url: 'https://imgur.com/JrK4iFo', breed: 'Alopekis'},
    {url: 'https://imgur.com/76BGnTp', breed: 'Alopekis'},
    {url: 'https://imgur.com/HuqCNPf', breed: 'Alsatian Shepalute'},
    {url: 'https://imgur.com/EEGSvFr', breed: 'Alsatian Shepalute'},
    {url: 'https://imgur.com/PL6S7nf', breed: 'American Bulldog'},
    {url: 'https://imgur.com/ShbwmNC', breed: 'American Bulldog'},
    {url: 'https://imgur.com/Yr10imO', breed: 'American Eskimo Dog'},
    {url: 'https://imgur.com/cNaQv02', breed: 'American Eskimo Dog'},
    {url: 'https://imgur.com/g6bCKc4', breed: 'American Fox Hound'},
    {url: 'https://imgur.com/SDo7KhP', breed: 'American Fox Hound'},
    {url: 'https://imgur.com/hFspNvb', breed: 'American Hairless Terrier'},
    {url: 'https://imgur.com/gsGjhBP', breed: 'American Hairless Terrier'},
    {url: 'https://imgur.com/zGXDPB2', breed: 'American Hairless Terrier'},
    {url: 'https://imgur.com/qjrQt6f', breed: 'American Hairless Terrier'},
    {url: 'https://imgur.com/cQ6mrKw', breed: 'Anatolian Shepherd Dog'},
    {url: 'https://imgur.com/6EkEh2G', breed: 'Anatolian Shepherd Dog'},
    {url: 'https://imgur.com/FHjytR2', breed: 'Appenzeller Sennenhund'},
    {url: 'https://imgur.com/CRlDWys', breed: 'Appenzeller Sennenhund'},
    {url: 'https://imgur.com/QDmor5B', breed: 'Appenzeller Sennenhund'},
    {url: 'https://imgur.com/WirOvax', breed: 'Ariege Pointer'},
    {url: 'https://imgur.com/DK2ZyFI', breed: 'Ariegois'},
    {url: 'https://imgur.com/cxBoTxV', breed: 'Ariegois'},
    {url: 'https://imgur.com/m6QEqi3', breed: 'Artois Hound'},
    {url: 'https://imgur.com/vWXFSqI', breed: 'Artois Hound'},
    {url: 'https://imgur.com/9eHd2ko', breed: 'Australian Silky Terrier'},
    {url: 'https://imgur.com/nasv1nl', breed: 'Australian Silky Terrier'},
    {url: 'https://imgur.com/q2UVtWH', breed: 'Australian Cattle Dog'},
    {url: 'https://imgur.com/z0WJxVr', breed: 'Australian Cattle Dog'},
    {url: 'https://imgur.com/COAOTYJ', breed: 'Australian Kelpie'},
    {url: 'https://imgur.com/chAiqSi', breed: 'Australian Kelpie'},
    {url: 'https://imgur.com/wiPoza8', breed: 'Australian Shepherd'},
    {url: 'https://imgur.com/UIEg1t6', breed: 'Australian Shepherd'},
    {url: 'https://imgur.com/K0hKFRq', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://imgur.com/s0A9ixq', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://imgur.com/MQ7pj4x', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://imgur.com/pr2YVCC', breed: 'Australian Terrier'},
    {url: 'https://imgur.com/Ktj5ROe', breed: 'Australian Terrier'},
    {url: 'https://imgur.com/AthA3cO', breed: 'Australian Terrier'},
    {url: 'https://imgur.com/2RZaSsy', breed: 'Australian Pinscher'},
    {url: 'https://imgur.com/NW9d6mV', breed: 'Australian Pinscher'},
    {url: 'https://imgur.com/PCYO75V', breed: 'Azawakh'},
    {url: 'https://imgur.com/j4m7PZD', breed: 'Bakharwal'},
    {url: 'https://imgur.com/BGR9ugF', breed: 'Bakharwal'},
    {url: 'https://imgur.com/W331XqM', breed: 'Barbet'},
    {url: 'https://imgur.com/GTLkMps', breed: 'Barbet'},
    {url: 'https://imgur.com/LDwFcOp', breed: 'Basenji'},
    {url: 'https://imgur.com/3PWSpST', breed: 'Basenji'},
    {url: 'https://imgur.com/bwhwwbz', breed: 'Basset Bleu de Gascogne'},
    {url: 'https://imgur.com/gi7mSB7', breed: 'Basset Hound'},
    {url: 'https://imgur.com/MdJBHZN', breed: 'Basset Hound'},
    {url: 'https://imgur.com/gcnh0pk', breed: 'Beagle'},
    {url: 'https://imgur.com/CmPeUHF', breed: 'Beagle'},
    {url: 'https://imgur.com/TbagKeE', breed: 'Bedlington Terrier'},
    {url: 'https://imgur.com/eG8aITX', breed: 'Bedlington Terrier'},
    {url: 'https://imgur.com/7P0E5hX', breed: 'Belgian Shepherd'},
    {url: 'https://imgur.com/OXhdrKs', breed: 'Bergamasco'},
    {url: 'https://imgur.com/KHBYfG9', breed: 'Bergamasco'},
    {url: 'https://imgur.com/ypERG01', breed: 'Bergamasco'},
    {url: 'https://imgur.com/nNIve2x', breed: 'Bernese Mountain Dog'},
    {url: 'https://imgur.com/BY1cd9i', breed: 'Bernese Mountain Dog'},
    {url: 'https://imgur.com/bf0bqjG', breed: 'Bichon Frise'},
    {url: 'https://imgur.com/29fk9mG', breed: 'Bichon Frise'},
    {url: 'https://imgur.com/zzOE0pf', breed: 'Blackmouth Cur'},
    {url: 'https://imgur.com/ZSH4Vk0', breed: 'Bloodhound'},
    {url: 'https://imgur.com/3flx6An', breed: 'Bloodhound'},
    {url: 'https://imgur.com/uBDiziP', breed: 'Bluetick Coonhound'},
    {url: 'https://imgur.com/htTNSnw', breed: 'Bluetick Coonhound'},
    {url: 'https://imgur.com/erMgkCh', breed: 'Bohemian Shepherd'},
    {url: 'https://imgur.com/L7KwCT9', breed: 'Bohemian Shepherd'},
    {url: 'https://imgur.com/mMPFkLS', breed: 'Bolognese Dog'},
    {url: 'https://imgur.com/iyUoQzJ', breed: 'Bolognese Dog'},
    {url: 'https://imgur.com/VgmQRgn', breed: 'Border Collie'},
    {url: 'https://imgur.com/Mc1hVAB', breed: 'Borzoi'},
    {url: 'https://imgur.com/RBrW62A', breed: 'Boston Terrier'},
    {url: 'https://imgur.com/je1rOHH', breed: 'Boston Terrier'},
    {url: 'https://imgur.com/a21s0il', breed: 'Boston Terrier'},
    {url: 'https://imgur.com/jLUTtW9', breed: 'Bouvier de Ardennes'},
    {url: 'https://imgur.com/ExoNBJJ', breed: 'Bouvier des Flandres'},
    {url: 'https://imgur.com/xIdWqBZ', breed: 'Boxer'},
    {url: 'https://imgur.com/YjZ6CcO', breed: 'Boxer'},
    {url: 'https://imgur.com/d0M4s53', breed: 'Bracco Italiano'},
    {url: 'https://imgur.com/bGkDvG2', breed: 'Bracco Italiano'},
    {url: 'https://imgur.com/tCi4m7r', breed: 'Brazilian Terrier'},
    {url: 'https://imgur.com/XMwkLls', breed: 'Bulldog'},
    {url: 'https://imgur.com/ZEzBB1h', breed: 'Bulldog'},
    {url: 'https://imgur.com/TBgcZE1', breed: 'Carolina Dog'},
    {url: 'https://imgur.com/m9gFpIB', breed: 'Carolina Dog'},
    {url: 'https://imgur.com/iW2ehjA', breed: 'Catahoula Cur'},
    {url: 'https://imgur.com/sV31VyV', breed: 'Cesky Fousek'},
    {url: 'https://imgur.com/5nvADpb', breed: 'Chihuahua'},
    {url: 'https://imgur.com/C4uzXhm', breed: 'Chihuahua'},
    {url: 'https://imgur.com/gmzpv5m', breed: 'Chinese Chongqing Dog'},
    {url: 'https://imgur.com/7trlXS9', breed: 'Chinese Chongqing Dog'},
    {url: 'https://imgur.com/tup84EF', breed: 'Chinese Crested Dog'},
    {url: 'https://imgur.com/a4XPiF4', breed: 'Chinese Crested Dog'},
    {url: 'https://imgur.com/7Opmx7y', breed: 'Chow Chow'},
    {url: 'https://imgur.com/0BiUJvS', breed: 'Chow Chow'},
    {url: 'https://imgur.com/SSFlPgo', breed: 'Cirnerco Delletna'},
    {url: 'https://imgur.com/qIgBzNc', breed: 'Cirnerco Delletna'},
    {url: 'https://imgur.com/9S65Qw1', breed: 'Cocker Spaniel'},
    {url: 'https://imgur.com/F8GWsh3', breed: 'Cocker Spaniel'},
    {url: 'https://imgur.com/djjx68O', breed: 'Cocker Spaniel'},
    {url: 'https://imgur.com/VPqwqaQ', breed: 'Corgi'},
    {url: 'https://imgur.com/2Y5oePw', breed: 'Corgi'},
    {url: 'https://imgur.com/Wen06BF', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://imgur.com/Mfq1pif', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://imgur.com/st717GT', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://imgur.com/ZSgy8uN', breed: 'Dachsund'},
    {url: 'https://imgur.com/oDXAMwd', breed: 'Dalmatian'},
    {url: 'https://imgur.com/gFCSV58', breed: 'Dalmatian'},
    {url: 'https://imgur.com/QgoBiBY', breed: 'Dandie Dinmont Terrier'},
    {url: 'https://imgur.com/2tLCRfd', breed: 'Dingo'},
    {url: 'https://imgur.com/veisRpE', breed: 'Dingo'},
    {url: 'https://imgur.com/fLWLmir', breed: 'Dingo'},
    {url: 'https://imgur.com/imDQB85', breed: 'Doberman'},
    {url: 'https://imgur.com/ZRcPzON', breed: 'Doberman'},
    {url: 'https://imgur.com/N3tWL4i', breed: 'Dogue de Bordeaux'},
    {url: 'https://imgur.com/n79LMrZ', breed: 'Dogue de Bordeaux'},
    {url: 'https://imgur.com/K36r9TA', breed: 'Finnish Spitz'},
    {url: 'https://imgur.com/g46dNIO', breed: 'Finnish Spitz'},
    {url: 'https://imgur.com/eiqmJ8b', breed: 'French Bulldog'},
    {url: 'https://imgur.com/u7Ax5MG', breed: 'French Bulldog'},
    {url: 'https://imgur.com/qPEDLnZ', breed: 'German Shepherd'},
    {url: 'https://imgur.com/gYn96eA', breed: 'German Shepherd'},
    {url: 'https://imgur.com/W3m4AQT', breed: 'Golden Retriever'},
    {url: 'https://imgur.com/QZSt8B8', breed: 'Golden Retriever'},
    {url: 'https://imgur.com/szPDUmb', breed: 'Great Dane'},
    {url: 'https://imgur.com/8BUJ35A', breed: 'Great Dane'},
    {url: 'https://imgur.com/qUHVe32', breed: 'Great Pyrenees'},
    {url: 'https://imgur.com/RvYFFl1', breed: 'Greyhound'},
    {url: 'https://imgur.com/zXU0byJ', breed: 'Greyhound'},
    {url: 'https://imgur.com/YSF0Qjz', breed: 'Husky'},
    {url: 'https://imgur.com/MEVNweJ', breed: 'Irish Setter'},
    {url: 'https://imgur.com/FMxstU8', breed: 'Jack Russell Terrier'},
    {url: 'https://imgur.com/pqLguhu', breed: 'Jack Russell Terrier'},
    {url: 'https://imgur.com/dB99ATn', breed: 'Japanese Chin'},
    {url: 'https://imgur.com/2yEH4ol', breed: 'Japanese Chin'},
    {url: 'https://imgur.com/Ws8ISTA', breed: 'Keeshond'},
    {url: 'https://imgur.com/k0uLhAz', breed: 'Keeshond'},
    {url: 'https://imgur.com/HLAd82w', breed: 'Komondor'},
    {url: 'https://imgur.com/wo4ZC8w', breed: 'Komondor'},
    {url: 'https://imgur.com/T68SsxM', breed: 'Koolie'},
    {url: 'https://imgur.com/LjDUuCZ', breed: 'Koolie'},
    {url: 'https://imgur.com/v1yCYlY', breed: 'Koolie'},
    {url: 'https://imgur.com/mqJj2Tr', breed: 'Korean Jindo Dog'},
    {url: 'https://imgur.com/LUeDqow', breed: 'Korean Jindo Dog'},
    {url: 'https://imgur.com/qnSm2J5', breed: 'Korean Mastiff'},
    {url: 'https://imgur.com/ys0r34F', breed: 'Labrador Retriever'},
    {url: 'https://imgur.com/InqLyXN', breed: 'Labrador Retriever'},
    {url: 'https://imgur.com/iQncRfk', breed: 'Lancashire Heeler'},
    {url: 'https://imgur.com/xhwivLA', breed: 'Leonberger'},
    {url: 'https://imgur.com/moGojf6', breed: 'Leonberger'},
    {url: 'https://imgur.com/PenKo5j', breed: 'Leonberger'},
    {url: 'https://imgur.com/60HQkz2', breed: 'Lhasa Apso'},
    {url: 'https://imgur.com/3dr1wKt', breed: 'Lowchen'},
    {url: 'https://imgur.com/MxMSdn8', breed: 'Maltese'},
    {url: 'https://imgur.com/hOSrYnM', breed: 'Maltese'},
    {url: 'https://imgur.com/KVAJTMi', breed: 'Mastiff'},
    {url: 'https://imgur.com/xFaHUF0', breed: 'Mastiff'},
    {url: 'https://imgur.com/xOXSwtt', breed: 'Miniature Pinscher'},
    {url: 'https://imgur.com/TCKiyx2', breed: 'Miniature Pinscher'},
    {url: 'https://imgur.com/E570FZm', breed: 'Newfoundland'},
    {url: 'https://imgur.com/NUrEMJp', breed: 'Newfoundland'},
    {url: 'https://imgur.com/0aZV3ic', breed: 'Norrbottenspets'},
    {url: 'https://imgur.com/oRT2FW4', breed: 'Norrbottenspets'},
    {url: 'https://imgur.com/vSR0DO5', breed: 'Norbottenspets'},
    {url: 'https://imgur.com/h5uotMU', breed: 'Norwegian Lundehund'},
    {url: 'https://imgur.com/C5AuWBt', breed: 'Norwegian Lundehund'},
    {url: 'https://imgur.com/L4i2uaO', breed: 'Norwegian Elkhound'},
    {url: 'https://imgur.com/VsORgqG', breed: 'Norwegian Elkhound'},
    {url: 'https://imgur.com/3FXF7bf', breed: 'Pachon Navarro'},
    {url: 'https://imgur.com/MyJKxtE', breed: 'Pachon Navarro'},
    {url: 'https://imgur.com/iSEi7Ny', breed: 'Pachon Navarro'},
    {url: 'https://imgur.com/Oqe5F5w', breed: 'Papillon'},
    {url: 'https://imgur.com/7oupGzp', breed: 'Papillon'},
    {url: 'https://imgur.com/ITQ8f73', breed: 'Pekingese'},
    {url: 'https://imgur.com/ZxPLgCZ', breed: 'Pekingese'},
    {url: 'https://imgur.com/OlJHzKs', breed: 'Pitbull'},
    {url: 'https://imgur.com/Rpnu6FN', breed: 'Pitbull'},
    {url: 'https://imgur.com/l5VRCal', breed: 'Pointer'},
    {url: 'https://imgur.com/Vl4a1vy', breed: 'Pointer'},
    {url: 'https://imgur.com/b0T3MiH', breed: 'Pomeranian'},
    {url: 'https://imgur.com/8PUBBSK', breed: 'Pomeranian'},
    {url: 'https://imgur.com/jmFFrFY', breed: 'Poodle'},
    {url: 'https://imgur.com/YMvVM1r', breed: 'Poodle'},
    {url: 'https://imgur.com/C3j6Xqw', breed: 'Poodle'},
    {url: 'https://imgur.com/zG2tXgo', breed: 'Pug'},
    {url: 'https://imgur.com/dZf9Fil', breed: 'Pug'},
    {url: 'https://imgur.com/XYJ8EDp', breed: 'Rhodesian Ridgeback'},
    {url: 'https://imgur.com/ZdcmWGE', breed: 'Rottweiler'},
    {url: 'https://imgur.com/z5vOGvh', breed: 'Rottweiler'},
    {url: 'https://imgur.com/rheQAhV', breed: 'Russkiy Toy'},
    {url: 'https://imgur.com/f2MP0lP', breed: 'Saint Bernard'},
    {url: 'https://imgur.com/FtKEFUR', breed: 'Saint Bernard'},
    {url: 'https://imgur.com/qWhp9mU', breed: 'Samoyed'},
    {url: 'https://imgur.com/QX7Yr3u', breed: 'Samoyed'},
    {url: 'https://imgur.com/DRLVYos', breed: 'Schipperke'},
    {url: 'https://imgur.com/OJbg7XI', breed: 'Schipperke'},
    {url: 'https://imgur.com/t0Oma3s', breed: 'Schnauzer'},
    {url: 'https://imgur.com/lRyRPB4', breed: 'Schnauzer'},
    {url: 'https://imgur.com/hRBESd1', breed: 'Scottish Terrier'},
    {url: 'https://imgur.com/ynlRdPW', breed: 'Scottish Terrier'},
    {url: 'https://imgur.com/NNyr40N', breed: 'Shar Pei'},
    {url: 'https://imgur.com/j26Wk7H', breed: 'Shar Pei'},
    {url: 'https://imgur.com/mtrcUwO', breed: 'Shar Pei'},
    {url: 'https://imgur.com/VSoAk6h', breed: 'Sheltie'},
    {url: 'https://imgur.com/ga9rMu8', breed: 'Sheltie'},
    {url: 'https://imgur.com/5aKoqRy', breed: 'Shiba Inu'},
    {url: 'https://imgur.com/IbX4h8O', breed: 'Shiba Inu'},
    {url: 'https://imgur.com/2ccJbcq', breed: 'Shiba Inu'},
    {url: 'https://imgur.com/G1JBUkB', breed: 'Shih Tzu'},
    {url: 'https://imgur.com/QZKM6h4', breed: 'Shih Tzu'},
    {url: 'https://imgur.com/0Ham2d0', breed: 'Shikoku'},
    {url: 'https://imgur.com/4Zr8At9', breed: 'Shikoku'},
    {url: 'https://imgur.com/6ahm3CN', breed: 'Siberian Laika'},
    {url: 'https://imgur.com/FNXA5oC', breed: 'Tibetan Mastiff'},
    {url: 'https://imgur.com/npNpVwS', breed: 'Tibetan Mastiff'},
    {url: 'https://imgur.com/maG0lnA', breed: 'Tibetan Mastiff'},
    {url: 'https://imgur.com/xVv9bbV', breed: 'Toy Poodle'},
    {url: 'https://imgur.com/dGJHGNe', breed: 'Toy Poodle'},
    {url: 'https://imgur.com/DLQN0Ef', breed: 'Vizsla'},
    {url: 'https://imgur.com/SvvrhVZ', breed: 'Weimaraner'},
    {url: 'https://imgur.com/FONInor', breed: 'Xolo Dog'},
    {url: 'https://imgur.com/CAtw9pR', breed: 'Xolo Dog'}
];