exports.dogs = [
    {url: 'https://i.imgur.com/vZpl0wz.jpg', breed: 'Affenpinscher'},
    {url: 'https://i.imgur.com/yJrmXwu.jpg', breed: 'Affenpinscher'},
    {url: 'https://i.imgur.com/toPER0k.jpg', breed: 'Afghan Hound'},
    {url: 'https://i.imgur.com/0GkxKPJ.jpg', breed: 'Afghan Hound'},
    {url: 'https://i.imgur.com/EiilTLI.jpg', breed: 'Africanis'},
    {url: 'https://i.imgur.com/SnGFAoL.jpg', breed: 'Africanis'},
    {url: 'https://i.imgur.com/so71NSQ.jpg', breed: 'Aidi'},
    {url: 'https://i.imgur.com/iL2Ik76.jpg', breed: 'Aidi'},
    {url: 'https://i.imgur.com/rhqps0L.jpg', breed: 'Airedale Terrier'},
    {url: 'https://i.imgur.com/mTAUQfY.jpg', breed: 'Airedale Terrier'},
    {url: 'https://i.imgur.com/kHWLhjJ.jpg', breed: 'Akbash Dog'},
    {url: 'https://i.imgur.com/0sEk0IX.jpg', breed: 'Akbash Dog'},
    {url: 'https://i.imgur.com/oeZOX9l.jpg', breed: 'Akita Inu'},
    {url: 'https://i.imgur.com/MBJC4VG.jpg', breed: 'Akita Inu'},
    {url: 'https://i.imgur.com/Vye1Jzc.jpg', breed: 'Akita Inu'},
    {url: 'https://i.imgur.com/JgR8S85.jpg', breed: 'Akita Inu'},
    {url: 'https://i.imgur.com/Bdak8bM.jpg', breed: 'Alangu Mastiff'},
    {url: 'https://i.imgur.com/tEWuHTd.jpg', breed: 'Alano Español'},
    {url: 'https://i.imgur.com/X8WORyf.jpg', breed: 'Alano Español'},
    {url: 'https://i.imgur.com/WUZhnHa.jpg', breed: 'Alano Español'},
    {url: 'https://i.imgur.com/ztiuoCv.jpg', breed: 'Alapaha Bulldog'},
    {url: 'https://i.imgur.com/aCUu1mK.jpg', breed: 'Alapaha Bulldog'},
    {url: 'https://i.imgur.com/65FcDmT.jpg', breed: 'Alaskan Klee Kai'},
    {url: 'https://i.imgur.com/A9xXCug.jpg', breed: 'Alaskan Klee Kai'},
    {url: 'https://i.imgur.com/8vlC6zu.jpg', breed: 'Alaskan Malamute'},
    {url: 'https://i.imgur.com/nUBEVNP.jpg', breed: 'Alaskan Malamute'},
    {url: 'https://i.imgur.com/JrK4iFo.jpg', breed: 'Alopekis'},
    {url: 'https://i.imgur.com/76BGnTp.jpg', breed: 'Alopekis'},
    {url: 'https://i.imgur.com/HuqCNPf.jpg', breed: 'Alsatian Shepalute'},
    {url: 'https://i.imgur.com/EEGSvFr.jpg', breed: 'Alsatian Shepalute'},
    {url: 'https://i.imgur.com/PL6S7nf.jpg', breed: 'American Bulldog'},
    {url: 'https://i.imgur.com/ShbwmNC.jpg', breed: 'American Bulldog'},
    {url: 'https://i.imgur.com/Yr10imO.jpg', breed: 'American Eskimo Dog'},
    {url: 'https://i.imgur.com/cNaQv02.jpg', breed: 'American Eskimo Dog'},
    {url: 'https://i.imgur.com/g6bCKc4.jpg', breed: 'American Fox Hound'},
    {url: 'https://i.imgur.com/SDo7KhP.jpg', breed: 'American Fox Hound'},
    {url: 'https://i.imgur.com/hFspNvb.jpg', breed: 'American Hairless Terrier'},
    {url: 'https://i.imgur.com/gsGjhBP.jpg', breed: 'American Hairless Terrier'},
    {url: 'https://i.imgur.com/zGXDPB2.jpg', breed: 'American Hairless Terrier'},
    {url: 'https://i.imgur.com/qjrQt6f.jpg', breed: 'American Hairless Terrier'},
    {url: 'https://i.imgur.com/cQ6mrKw.jpg', breed: 'Anatolian Shepherd Dog'},
    {url: 'https://i.imgur.com/6EkEh2G.jpg', breed: 'Anatolian Shepherd Dog'},
    {url: 'https://i.imgur.com/FHjytR2.jpg', breed: 'Appenzeller Sennenhund'},
    {url: 'https://i.imgur.com/CRlDWys.jpg', breed: 'Appenzeller Sennenhund'},
    {url: 'https://i.imgur.com/QDmor5B.jpg', breed: 'Appenzeller Sennenhund'},
    {url: 'https://i.imgur.com/WirOvax.jpg', breed: 'Ariege Pointer'},
    {url: 'https://i.imgur.com/DK2ZyFI.jpg', breed: 'Ariegois'},
    {url: 'https://i.imgur.com/cxBoTxV.jpg', breed: 'Ariegois'},
    {url: 'https://i.imgur.com/m6QEqi3.jpg', breed: 'Artois Hound'},
    {url: 'https://i.imgur.com/vWXFSqI.jpg', breed: 'Artois Hound'},
    {url: 'https://i.imgur.com/9eHd2ko.jpg', breed: 'Australian Silky Terrier'},
    {url: 'https://i.imgur.com/nasv1nl.jpg', breed: 'Australian Silky Terrier'},
    {url: 'https://i.imgur.com/q2UVtWH.jpg', breed: 'Australian Cattle Dog'},
    {url: 'https://i.imgur.com/z0WJxVr.jpg', breed: 'Australian Cattle Dog'},
    {url: 'https://i.imgur.com/COAOTYJ.jpg', breed: 'Australian Kelpie'},
    {url: 'https://i.imgur.com/chAiqSi.jpg', breed: 'Australian Kelpie'},
    {url: 'https://i.imgur.com/wiPoza8.jpg', breed: 'Australian Shepherd'},
    {url: 'https://i.imgur.com/UIEg1t6.jpg', breed: 'Australian Shepherd'},
    {url: 'https://i.imgur.com/K0hKFRq.jpg', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://i.imgur.com/s0A9ixq.jpg', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://i.imgur.com/MQ7pj4x.jpg', breed: 'Australian Stumpy Tail Cattle Dog'},
    {url: 'https://i.imgur.com/pr2YVCC.jpg', breed: 'Australian Terrier'},
    {url: 'https://i.imgur.com/Ktj5ROe.jpg', breed: 'Australian Terrier'},
    {url: 'https://i.imgur.com/AthA3cO.jpg', breed: 'Australian Terrier'},
    {url: 'https://i.imgur.com/2RZaSsy.jpg', breed: 'Australian Pinscher'},
    {url: 'https://i.imgur.com/NW9d6mV.jpg', breed: 'Australian Pinscher'},
    {url: 'https://i.imgur.com/PCYO75V.jpg', breed: 'Azawakh'},
    {url: 'https://i.imgur.com/j4m7PZD.jpg', breed: 'Bakharwal'},
    {url: 'https://i.imgur.com/BGR9ugF.jpg', breed: 'Bakharwal'},
    {url: 'https://i.imgur.com/W331XqM.jpg', breed: 'Barbet'},
    {url: 'https://i.imgur.com/GTLkMps.jpg', breed: 'Barbet'},
    {url: 'https://i.imgur.com/LDwFcOp.jpg', breed: 'Basenji'},
    {url: 'https://i.imgur.com/3PWSpST.jpg', breed: 'Basenji'},
    {url: 'https://i.imgur.com/bwhwwbz.jpg', breed: 'Basset Bleu de Gascogne'},
    {url: 'https://i.imgur.com/gi7mSB7.jpg', breed: 'Basset Hound'},
    {url: 'https://i.imgur.com/MdJBHZN.jpg', breed: 'Basset Hound'},
    {url: 'https://i.imgur.com/gcnh0pk.jpg', breed: 'Beagle'},
    {url: 'https://i.imgur.com/CmPeUHF.jpg', breed: 'Beagle'},
    {url: 'https://i.imgur.com/TbagKeE.jpg', breed: 'Bedlington Terrier'},
    {url: 'https://i.imgur.com/eG8aITX.jpg', breed: 'Bedlington Terrier'},
    {url: 'https://i.imgur.com/7P0E5hX.jpg', breed: 'Belgian Shepherd'},
    {url: 'https://i.imgur.com/OXhdrKs.jpg', breed: 'Bergamasco'},
    {url: 'https://i.imgur.com/KHBYfG9.jpg', breed: 'Bergamasco'},
    {url: 'https://i.imgur.com/ypERG01.jpg', breed: 'Bergamasco'},
    {url: 'https://i.imgur.com/nNIve2x.jpg', breed: 'Bernese Mountain Dog'},
    {url: 'https://i.imgur.com/BY1cd9i.jpg', breed: 'Bernese Mountain Dog'},
    {url: 'https://i.imgur.com/bf0bqjG.jpg', breed: 'Bichon Frise'},
    {url: 'https://i.imgur.com/29fk9mG.jpg', breed: 'Bichon Frise'},
    {url: 'https://i.imgur.com/zzOE0pf.jpg', breed: 'Blackmouth Cur'},
    {url: 'https://i.imgur.com/ZSH4Vk0.jpg', breed: 'Bloodhound'},
    {url: 'https://i.imgur.com/3flx6An.jpg', breed: 'Bloodhound'},
    {url: 'https://i.imgur.com/uBDiziP.jpg', breed: 'Bluetick Coonhound'},
    {url: 'https://i.imgur.com/htTNSnw.jpg', breed: 'Bluetick Coonhound'},
    {url: 'https://i.imgur.com/erMgkCh.jpg', breed: 'Bohemian Shepherd'},
    {url: 'https://i.imgur.com/L7KwCT9.jpg', breed: 'Bohemian Shepherd'},
    {url: 'https://i.imgur.com/mMPFkLS.jpg', breed: 'Bolognese Dog'},
    {url: 'https://i.imgur.com/iyUoQzJ.jpg', breed: 'Bolognese Dog'},
    {url: 'https://i.imgur.com/VgmQRgn.jpg', breed: 'Border Collie'},
    {url: 'https://i.imgur.com/Mc1hVAB.jpg', breed: 'Borzoi'},
    {url: 'https://i.imgur.com/RBrW62A.jpg', breed: 'Boston Terrier'},
    {url: 'https://i.imgur.com/je1rOHH.jpg', breed: 'Boston Terrier'},
    {url: 'https://i.imgur.com/a21s0il.jpg', breed: 'Boston Terrier'},
    {url: 'https://i.imgur.com/jLUTtW9.jpg', breed: 'Bouvier de Ardennes'},
    {url: 'https://i.imgur.com/ExoNBJJ.jpg', breed: 'Bouvier des Flandres'},
    {url: 'https://i.imgur.com/xIdWqBZ.jpg', breed: 'Boxer'},
    {url: 'https://i.imgur.com/YjZ6CcO.jpg', breed: 'Boxer'},
    {url: 'https://i.imgur.com/d0M4s53.jpg', breed: 'Bracco Italiano'},
    {url: 'https://i.imgur.com/bGkDvG2.jpg', breed: 'Bracco Italiano'},
    {url: 'https://i.imgur.com/tCi4m7r.jpg', breed: 'Brazilian Terrier'},
    {url: 'https://i.imgur.com/XMwkLls.jpg', breed: 'Bulldog'},
    {url: 'https://i.imgur.com/ZEzBB1h.jpg', breed: 'Bulldog'},
    {url: 'https://i.imgur.com/TBgcZE1.jpg', breed: 'Carolina Dog'},
    {url: 'https://i.imgur.com/m9gFpIB.jpg', breed: 'Carolina Dog'},
    {url: 'https://i.imgur.com/iW2ehjA.jpg', breed: 'Catahoula Cur'},
    {url: 'https://i.imgur.com/sV31VyV.jpg', breed: 'Cesky Fousek'},
    {url: 'https://i.imgur.com/5nvADpb.jpg', breed: 'Chihuahua'},
    {url: 'https://i.imgur.com/C4uzXhm.jpg', breed: 'Chihuahua'},
    {url: 'https://i.imgur.com/gmzpv5m.jpg', breed: 'Chinese Chongqing Dog'},
    {url: 'https://i.imgur.com/7trlXS9.jpg', breed: 'Chinese Chongqing Dog'},
    {url: 'https://i.imgur.com/tup84EF.jpg', breed: 'Chinese Crested Dog'},
    {url: 'https://i.imgur.com/a4XPiF4.jpg', breed: 'Chinese Crested Dog'},
    {url: 'https://i.imgur.com/7Opmx7y.jpg', breed: 'Chow Chow'},
    {url: 'https://i.imgur.com/0BiUJvS.jpg', breed: 'Chow Chow'},
    {url: 'https://i.imgur.com/SSFlPgo.jpg', breed: 'Cirnerco Delletna'},
    {url: 'https://i.imgur.com/qIgBzNc.jpg', breed: 'Cirnerco Delletna'},
    {url: 'https://i.imgur.com/9S65Qw1.jpg', breed: 'Cocker Spaniel'},
    {url: 'https://i.imgur.com/F8GWsh3.jpg', breed: 'Cocker Spaniel'},
    {url: 'https://i.imgur.com/djjx68O.jpg', breed: 'Cocker Spaniel'},
    {url: 'https://i.imgur.com/VPqwqaQ.jpg', breed: 'Corgi'},
    {url: 'https://i.imgur.com/2Y5oePw.jpg', breed: 'Corgi'},
    {url: 'https://i.imgur.com/Wen06BF.jpg', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://i.imgur.com/Mfq1pif.jpg', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://i.imgur.com/st717GT.jpg', breed: 'Czechoslovakian Wolf Dog'},
    {url: 'https://i.imgur.com/ZSgy8uN.jpg', breed: 'Dachsund'},
    {url: 'https://i.imgur.com/oDXAMwd.jpg', breed: 'Dalmatian'},
    {url: 'https://i.imgur.com/gFCSV58.jpg', breed: 'Dalmatian'},
    {url: 'https://i.imgur.com/QgoBiBY.jpg', breed: 'Dandie Dinmont Terrier'},
    {url: 'https://i.imgur.com/2tLCRfd.jpg', breed: 'Dingo'},
    {url: 'https://i.imgur.com/veisRpE.jpg', breed: 'Dingo'},
    {url: 'https://i.imgur.com/fLWLmir.jpg', breed: 'Dingo'},
    {url: 'https://i.imgur.com/imDQB85.jpg', breed: 'Doberman'},
    {url: 'https://i.imgur.com/ZRcPzON.jpg', breed: 'Doberman'},
    {url: 'https://i.imgur.com/N3tWL4i.jpg', breed: 'Dogue de Bordeaux'},
    {url: 'https://i.imgur.com/n79LMrZ.jpg', breed: 'Dogue de Bordeaux'},
    {url: 'https://i.imgur.com/K36r9TA.jpg', breed: 'Finnish Spitz'},
    {url: 'https://i.imgur.com/g46dNIO.jpg', breed: 'Finnish Spitz'},
    {url: 'https://i.imgur.com/eiqmJ8b.jpg', breed: 'French Bulldog'},
    {url: 'https://i.imgur.com/u7Ax5MG.jpg', breed: 'French Bulldog'},
    {url: 'https://i.imgur.com/qPEDLnZ.jpg', breed: 'German Shepherd'},
    {url: 'https://i.imgur.com/gYn96eA.jpg', breed: 'German Shepherd'},
    {url: 'https://i.imgur.com/W3m4AQT.jpg', breed: 'Golden Retriever'},
    {url: 'https://i.imgur.com/ETcR90g.jpg', breed: 'Golden Retriever'},
    {url: 'https://i.imgur.com/szPDUmb.jpg', breed: 'Great Dane'},
    {url: 'https://i.imgur.com/8BUJ35A.jpg', breed: 'Great Dane'},
    {url: 'https://i.imgur.com/qUHVe32.jpg', breed: 'Great Pyrenees'},
    {url: 'https://i.imgur.com/RvYFFl1.jpg', breed: 'Greyhound'},
    {url: 'https://i.imgur.com/zXU0byJ.jpg', breed: 'Greyhound'},
    {url: 'https://i.imgur.com/YSF0Qjz.jpg', breed: 'Husky'},
    {url: 'https://i.imgur.com/MEVNweJ.jpg', breed: 'Irish Setter'},
    {url: 'https://i.imgur.com/FMxstU8.jpg', breed: 'Jack Russell Terrier'},
    {url: 'https://i.imgur.com/pqLguhu.jpg', breed: 'Jack Russell Terrier'},
    {url: 'https://i.imgur.com/dB99ATn.jpg', breed: 'Japanese Chin'},
    {url: 'https://i.imgur.com/2yEH4ol.jpg', breed: 'Japanese Chin'},
    {url: 'https://i.imgur.com/Ws8ISTA.jpg', breed: 'Keeshond'},
    {url: 'https://i.imgur.com/k0uLhAz.jpg', breed: 'Keeshond'},
    {url: 'https://i.imgur.com/HLAd82w.jpg', breed: 'Komondor'},
    {url: 'https://i.imgur.com/wo4ZC8w.jpg', breed: 'Komondor'},
    {url: 'https://i.imgur.com/T68SsxM.jpg', breed: 'Koolie'},
    {url: 'https://i.imgur.com/LjDUuCZ.jpg', breed: 'Koolie'},
    {url: 'https://i.imgur.com/v1yCYlY.jpg', breed: 'Koolie'},
    {url: 'https://i.imgur.com/mqJj2Tr.jpg', breed: 'Korean Jindo Dog'},
    {url: 'https://i.imgur.com/LUeDqow.jpg', breed: 'Korean Jindo Dog'},
    {url: 'https://i.imgur.com/qnSm2J5.jpg', breed: 'Korean Mastiff'},
    {url: 'https://i.imgur.com/ys0r34F.jpg', breed: 'Labrador Retriever'},
    {url: 'https://i.imgur.com/InqLyXN.jpg', breed: 'Labrador Retriever'},
    {url: 'https://i.imgur.com/iQncRfk.jpg', breed: 'Lancashire Heeler'},
    {url: 'https://i.imgur.com/xhwivLA.jpg', breed: 'Leonberger'},
    {url: 'https://i.imgur.com/moGojf6.jpg', breed: 'Leonberger'},
    {url: 'https://i.imgur.com/PenKo5j.jpg', breed: 'Leonberger'},
    {url: 'https://i.imgur.com/60HQkz2.jpg', breed: 'Lhasa Apso'},
    {url: 'https://i.imgur.com/3dr1wKt.jpg', breed: 'Lowchen'},
    {url: 'https://i.imgur.com/MxMSdn8.jpg', breed: 'Maltese'},
    {url: 'https://i.imgur.com/hOSrYnM.jpg', breed: 'Maltese'},
    {url: 'https://i.imgur.com/KVAJTMi.jpg', breed: 'Mastiff'},
    {url: 'https://i.imgur.com/xFaHUF0.jpg', breed: 'Mastiff'},
    {url: 'https://i.imgur.com/xOXSwtt.jpg', breed: 'Miniature Pinscher'},
    {url: 'https://i.imgur.com/TCKiyx2.jpg', breed: 'Miniature Pinscher'},
    {url: 'https://i.imgur.com/E570FZm.jpg', breed: 'Newfoundland'},
    {url: 'https://i.imgur.com/NUrEMJp.jpg', breed: 'Newfoundland'},
    {url: 'https://i.imgur.com/0aZV3ic.jpg', breed: 'Norrbottenspets'},
    {url: 'https://i.imgur.com/oRT2FW4.jpg', breed: 'Norrbottenspets'},
    {url: 'https://i.imgur.com/vSR0DO5.jpg', breed: 'Norbottenspets'},
    {url: 'https://i.imgur.com/h5uotMU.jpg', breed: 'Norwegian Lundehund'},
    {url: 'https://i.imgur.com/C5AuWBt.jpg', breed: 'Norwegian Lundehund'},
    {url: 'https://i.imgur.com/L4i2uaO.jpg', breed: 'Norwegian Elkhound'},
    {url: 'https://i.imgur.com/VsORgqG.jpg', breed: 'Norwegian Elkhound'},
    {url: 'https://i.imgur.com/3FXF7bf.jpg', breed: 'Pachon Navarro'},
    {url: 'https://i.imgur.com/MyJKxtE.jpg', breed: 'Pachon Navarro'},
    {url: 'https://i.imgur.com/iSEi7Ny.jpg', breed: 'Pachon Navarro'},
    {url: 'https://i.imgur.com/Oqe5F5w.jpg', breed: 'Papillon'},
    {url: 'https://i.imgur.com/7oupGzp.jpg', breed: 'Papillon'},
    {url: 'https://i.imgur.com/ITQ8f73.jpg', breed: 'Pekingese'},
    {url: 'https://i.imgur.com/ZxPLgCZ.jpg', breed: 'Pekingese'},
    {url: 'https://i.imgur.com/OlJHzKs.jpg', breed: 'Pitbull'},
    {url: 'https://i.imgur.com/Rpnu6FN.jpg', breed: 'Pitbull'},
    {url: 'https://i.imgur.com/l5VRCal.jpg', breed: 'Pointer'},
    {url: 'https://i.imgur.com/Vl4a1vy.jpg', breed: 'Pointer'},
    {url: 'https://i.imgur.com/b0T3MiH.jpg', breed: 'Pomeranian'},
    {url: 'https://i.imgur.com/8PUBBSK.jpg', breed: 'Pomeranian'},
    {url: 'https://i.imgur.com/jmFFrFY.jpg', breed: 'Poodle'},
    {url: 'https://i.imgur.com/YMvVM1r.jpg', breed: 'Poodle'},
    {url: 'https://i.imgur.com/C3j6Xqw.jpg', breed: 'Poodle'},
    {url: 'https://i.imgur.com/zG2tXgo.jpg', breed: 'Pug'},
    {url: 'https://i.imgur.com/dZf9Fil.jpg', breed: 'Pug'},
    {url: 'https://i.imgur.com/XYJ8EDp.jpg', breed: 'Rhodesian Ridgeback'},
    {url: 'https://i.imgur.com/ZdcmWGE.jpg', breed: 'Rottweiler'},
    {url: 'https://i.imgur.com/z5vOGvh.jpg', breed: 'Rottweiler'},
    {url: 'https://i.imgur.com/rheQAhV.jpg', breed: 'Russkiy Toy'},
    {url: 'https://i.imgur.com/f2MP0lP.jpg', breed: 'Saint Bernard'},
    {url: 'https://i.imgur.com/FtKEFUR.jpg', breed: 'Saint Bernard'},
    {url: 'https://i.imgur.com/qWhp9mU.jpg', breed: 'Samoyed'},
    {url: 'https://i.imgur.com/QX7Yr3u.jpg', breed: 'Samoyed'},
    {url: 'https://i.imgur.com/DRLVYos.jpg', breed: 'Schipperke'},
    {url: 'https://i.imgur.com/OJbg7XI.jpg', breed: 'Schipperke'},
    {url: 'https://i.imgur.com/t0Oma3s.jpg', breed: 'Schnauzer'},
    {url: 'https://i.imgur.com/lRyRPB4.jpg', breed: 'Schnauzer'},
    {url: 'https://i.imgur.com/hRBESd1.jpg', breed: 'Scottish Terrier'},
    {url: 'https://i.imgur.com/ynlRdPW.jpg', breed: 'Scottish Terrier'},
    {url: 'https://i.imgur.com/NNyr40N.jpg', breed: 'Shar Pei'},
    {url: 'https://i.imgur.com/j26Wk7H.jpg', breed: 'Shar Pei'},
    {url: 'https://i.imgur.com/mtrcUwO.jpg', breed: 'Shar Pei'},
    {url: 'https://i.imgur.com/VSoAk6h.jpg', breed: 'Sheltie'},
    {url: 'https://i.imgur.com/ga9rMu8.jpg', breed: 'Sheltie'},
    {url: 'https://i.imgur.com/5aKoqRy.jpg', breed: 'Shiba Inu'},
    {url: 'https://i.imgur.com/IbX4h8O.jpg', breed: 'Shiba Inu'},
    {url: 'https://i.imgur.com/2ccJbcq.jpg', breed: 'Shiba Inu'},
    {url: 'https://i.imgur.com/G1JBUkB.jpg', breed: 'Shih Tzu'},
    {url: 'https://i.imgur.com/QZKM6h4.jpg', breed: 'Shih Tzu'},
    {url: 'https://i.imgur.com/0Ham2d0.jpg', breed: 'Shikoku'},
    {url: 'https://i.imgur.com/4Zr8At9.jpg', breed: 'Shikoku'},
    {url: 'https://i.imgur.com/6ahm3CN.jpg', breed: 'Siberian Laika'},
    {url: 'https://i.imgur.com/FNXA5oC.jpg', breed: 'Tibetan Mastiff'},
    {url: 'https://i.imgur.com/npNpVwS.jpg', breed: 'Tibetan Mastiff'},
    {url: 'https://i.imgur.com/maG0lnA.jpg', breed: 'Tibetan Mastiff'},
    {url: 'https://i.imgur.com/xVv9bbV.jpg', breed: 'Toy Poodle'},
    {url: 'https://i.imgur.com/dGJHGNe.jpg', breed: 'Toy Poodle'},
    {url: 'https://i.imgur.com/DLQN0Ef.jpg', breed: 'Vizsla'},
    {url: 'https://i.imgur.com/SvvrhVZ.jpg', breed: 'Weimaraner'},
    {url: 'https://i.imgur.com/FONInor.jpg', breed: 'Xolo Dog'},
    {url: 'https://i.imgur.com/CAtw9pR.jpg', breed: 'Xolo Dog'}
];